repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Update this to the latest version if needed
    hooks:
      - id: prettier
        args: ["--write"]
        files: "\\.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$" # Specify file types
        stages: [pre-commit]
