name: Bump version, release, and publish

permissions:
  contents: write

on:
  push:
    branches:
      - test-commitizen

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Get current version from package.json
        id: get_current_version
        run: |
          PREVIOUS_VERSION=$(jq -r .version package.json)
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      - name: Handle if version changed
        if: env.REVISION != env.PREVIOUS_VERSION
        run: |
          echo "The version has changed."
      # - name: Create GH Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body_path: "body.md"
      #     tag_name: ${{ env.REVISION }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Authenticate with npm
      #   run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      # - name: Publish to npm
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     npm publish --access public  # Publish the package to npm
